# Generated by Django 5.2.12 on 2026-03-29 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoqueprodutos',
            options={'verbose_name': 'Estoque de Produtos', 'verbose_name_plural': 'Estoques de Produtos'},
        ),
        migrations.AlterModelOptions(
            name='itenspedido',
            options={'verbose_name': 'Item de Pedido', 'verbose_name_plural': 'Itens de Pedido'},
        ),
        migrations.AlterModelOptions(
            name='pedidos',
            options={'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AddField(
            model_name='itenspedido',
            name='adicionais',
            field=models.JSONField(blank=True, default=list, verbose_name='Adicionais (Snapshot)'),
        ),
    ]
