# Generated by Django 5.2.12 on 2026-03-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_estoqueprodutos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itenspedido',
            name='adicionais',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
