# Generated by Django 5.2.12 on 2026-03-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_itenspedido_adicionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='status',
            field=models.CharField(choices=[('PAGO', 'Pago'), ('PREPARO', 'Em Preparo'), ('ENTREGA', 'Em Entrega'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PAGO', max_length=20),
        ),
    ]
