# Generated by Django 5.2.12 on 2026-03-30 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pedidos_cep_pedidos_cpf_pedidos_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=9)),
                ('ativo', models.BooleanField(default=True)),
                ('produtos', models.ManyToManyField(related_name='adicionais_disponiveis', to='core.produtos')),
            ],
        ),
        migrations.CreateModel(
            name='PratoDoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Segunda-feira'), (1, 'Terça-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sábado'), (6, 'Domingo')])),
                ('ativo', models.BooleanField(default=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_prato_dia', to='core.produtos')),
            ],
        ),
    ]
