# Generated by Django 5.2.12 on 2026-04-05 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adicional_pratododia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adicional',
            options={'verbose_name': 'Adicional', 'verbose_name_plural': 'Adicionais'},
        ),
        migrations.CreateModel(
            name='PratoDiaMaisClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('quantidade', models.IntegerField(default=0)),
                ('prato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks_pratos', to='core.pratododia')),
            ],
            options={
                'verbose_name': 'Prato do dia mais clicado',
                'verbose_name_plural': 'Pratos do dia mais clicados',
            },
        ),
        migrations.CreateModel(
            name='ProdutosMaisClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('quantidade', models.IntegerField(default=0)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks_produtos', to='core.produtos')),
            ],
            options={
                'verbose_name': 'Produto mais clicado',
                'verbose_name_plural': 'Produtos mais clicados',
            },
        ),
    ]
