# Generated by Django 5.2.12 on 2026-04-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_adicional_options_pratodiamaisclick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='entrega',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='impresso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='nome_cliente',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='rua',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
