# Generated by Django 5.2.12 on 2026-04-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pedidos_entrega_pedidos_impresso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix'), ('CARTAO', 'Cartão'), ('MISTO', 'Misto')], default='PIX', max_length=20),
        ),
    ]
