# Generated by Django 5.2.12 on 2026-04-18 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pedidos_forma_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnderecoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('atualizado', models.DateTimeField(auto_now=True, null=True)),
                ('rua', models.CharField(max_length=150)),
                ('cep', models.CharField(max_length=16)),
                ('numero', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Endereço da loja',
                'verbose_name_plural': 'Endereços das lojas',
            },
        ),
        migrations.AddField(
            model_name='pedidos',
            name='taxa_motoca',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Taxa Motoca'),
        ),
    ]
