# Generated by Django 5.0.14 on 2026-04-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_enderecoloja_pedidos_taxa_motoca'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
