# Generated by Django 5.2.8 on 2026-09-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_sincronizar_sequences_pdv"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="pedidos",
            index=models.Index(fields=["criado_em"], name="pedido_criado_idx"),
        ),
        migrations.AddIndex(
            model_name="pedidos",
            index=models.Index(
                fields=["status", "criado_em"], name="pedido_status_criado_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pedidos",
            index=models.Index(fields=["impresso"], name="pedido_impresso_idx"),
        ),
    ]
